swagger: "2.0"
info:
    title: Argent Bank Transaction API
    description: API model proposal for user transactions
    version: 2.0.0
    termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
    - http
paths:
    /user/transactions:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transactions Current Month API
            description: API for fetching current month transactions
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: User transactions retrieved successfully
                    schema:
                        $ref: "#/definitions/allTransactionsResponse"
                "401":
                    description: Unauthorized
                "404":
                    description: Transactions not found
                "500":
                    description: Internal Server Error
    /user/transaction/{idTransaction}:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transaction Show API
            description: API for showing a transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: idTransaction
                  description: Id of the transaction
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction retrieved successfully
                    schema:
                        $ref: "#/definitions/ApiTransactionResponse"
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transaction Edit API
            description: API for updating a transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: idTransaction
                  description: Id of the transaction that needs to be edited
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Edit transaction
                  required: true
                  schema:
                      $ref: "#/definitions/editTransaction"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction edited successfully
                    schema:
                        $ref: "#/definitions/ApiTransactionResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    allTransactionsResponse:
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    accounts_0:
                        type: array
                        items:
                            type: object
                            properties:
                                id:
                                    type: string
                                    description: Id of the account
                                transactions:
                                    type: array
                                    items:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                description: Id of the first transaction
                                            date:
                                                type: string
                                                description: Date of the first transaction
                                            amount:
                                                type: number
                                                description: Amount of the first transaction
                                            description:
                                                type: string
                                                description: Description of the first transaction
                                            category:
                                                type: string
                                                description: Category of the first transaction
                                            notes:
                                                type: string
                                                description: Notes of the first transaction
                    accounts_1:
                        type: array
                        items:
                            type: object
                            properties:
                                id:
                                    type: string
                                    description: Id of the account                            
                                transactions:
                                    type: array
                                    items:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                description: Id of the second transaction
                                            date:
                                                type: string
                                                description: Date of the second transaction
                                            amount:
                                                type: number
                                                description: Amount of the second transaction
                                            description:
                                                type: string
                                                description: Description of the second transaction
                                            category:
                                                type: string
                                                description: Category of the second transaction
                                            notes:
                                                type: string
                                                description: Notes of the second transaction
                    accounts_2:
                        type: array
                        items:
                            type: object
                            properties:
                                id:
                                    type: string
                                    description: Id of the account                            
                                transactions:
                                    type: array
                                    items:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                description: Id of the third transaction
                                            date:
                                                type: string
                                                description: Date of the third transaction
                                            amount:
                                                type: number
                                                description: Amount of the third transaction
                                            description:
                                                type: string
                                                description: Description of the third transaction
                                            category:
                                                type: string
                                                description: Category of the third transaction
                                            notes:
                                                type: string
                                                description: Notes of the third transaction
    ApiTransactionResponse:
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                        description: Id of the transaction
                    date:
                        type: string
                        description: Date of the transaction
                    amount:
                        type: number
                        description: Amount of the transaction
                    description:
                        type: string
                        description: Description of the transaction
                    category:
                        type: string
                        description: Category of the transaction
                    notes:
                        type: string
                        description: Notes of the transaction
    editTransaction:
        properties:
            category:
                type: string
                description: New category of this transaction
            notes:
                type: string
                description: New notes of this transaction